name: Deploy to ECR
on: 
  push:
    branches: [master]
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code into node directory
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1


    - name: Load secrets and save to .env
      run: |
        aws secretsmanager get-secret-value --secret-id <AWS-SECRET-NAME> --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > .env

    - name: Deploy to AWS Lambda
      run: |
        npm install
        npm run deploy
